services:
    db:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: wsc-webtech
            MYSQL_ROOT_PASSWORD: P@ssw0rd
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3307:3306

    app:
        build: .
        container_name: wsc-app
        image: ${DOCKER_USERNAME}/wsc-app:latest
        restart: unless-stopped
        environment:
            DB_HOST: mysql
            DB_DATABASE: wsc-webtech
        depends_on:
            - db
        ports:
            - 8000:80
        volumes:
            - .env:/var/www/html/.env
            - app_storage:/var/www/html/storage

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        container_name: phpmyadmin
        ports:
            - 8001:80
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd

volumes:
    mysql_data:
    app_storage:
